package:
  name: pyepics
  version: "3.2.5rc3"

source:
  git_rev: 3.2.5rc3
  git_url:  https://github.com/pyepics/pyepics.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - pyparsing

test:
  # Python imports
  imports:
    - epics
    - epics.autosave
    - epics.compat
    - epics.devices

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pyepics.github.io/pyepics/
  license: Epics Open License
  summary: 'Epics Channel Access for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
